### ISSUE TITLE
Header profile info incorrect.

### ISSUE THREAD

**Issue by MikeChipshop** [MikeChipshop/PB#22]
Avatar and profile name.

**Comment by Siizumi** [comment]
?

**Comment by MikeChipshop** [comment]
Don't worry. Opened as a bug so i can work it in to the development.

**Comment by MikeChipshop** [comment]
Complication has arisen with this where there's a conflict between Woo and WP. Where it appears you have to use Woo, yet we're not ready to use Woo just yet.

Looking for work arounds.
