### ISSUE TITLE
Address details visible on newsletter signup confirmation

### ISSUE THREAD

**Issue by Siizumi** [MikeChipshop/PB#59]
Can we get rid pls? I'd prefer not to have them on there if possible. Do you have the log ins for MC to take a look?

It'd be good to add some branding to the notifications & auto responses too if we can.

Thoughts?

**Comment by MikeChipshop** [comment]
Taking a look as we speak. Going to split the branding part off in to a separate task to keep it simple.

**Comment by MikeChipshop** [comment]
Apparently addresses are required by European spam laws. I've tried my best to make it as non-specific as possible.
